const words = [
    {preposition: 'das',
    word: 'Problem',
    transcription: '[proˈbleːm]',
    translation: 'Проблема'},
    {preposition: 'die',
    word: 'Arbeit',
    transcription: '[ˈaʁbaɪ̯t]',
    translation: 'Работа'},
    {preposition: 'die',
    word: 'Liebe',
    transcription: '[ˈliːbə]',
    translation: 'Любовь'},
    {preposition: 'der',
    word: 'Traum',
    transcription: '[tʁaʊ̯m]',
    translation: 'Мечта'},
    {preposition: 'das',
    word: 'Essen',
    transcription: '[ˈɛsn̩]',
    translation: 'Еда'},
    {preposition: 'die',
    word: 'Hochzeit',
    transcription: '[ˈhɔˌʦaɪ̯t]',
    translation: 'Свадьба'},
    {preposition: 'das',
    word: 'Kleid',
    transcription: '[klaɪ̯t]',
    translation: 'Платье'},
    {preposition: 'der',
    word: 'Computer',
    transcription: '[kɔmˈpjuːtɐ]',
    translation: 'Компьютер'},
    {preposition: 'die',
    word: 'Chefin',
    transcription: '[ˈʃɛfɪn]',
    translation: 'Начальница'},
    {preposition: 'das',
    word: 'Jahr',
    transcription: 'ˈjaːɐ̯',
    translation: 'Год'}
  ];

  export default words;